stages:
  - check
  - deploy

before_script:
  - dmenv install

check/linux/nightly:
  stage: check
  only:
    - schedules
  script:
    - xvfb-run dmenv run -- python run-ci.py check --runner linux --nightly
  tags:
    - linux

check/macos/nightly:
  stage: check
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py check --runner macos --nightly
  tags:
    - macos

.deploy:
  stage: deploy
  except:
    - schedules
  tags:
    - linux

deploy/sdk:
  extends: .deploy
  environment:
    name: prod
  only:
    - /\Av[0-9.]+(-(alpha|beta)[0-9]+)?\z/
  script:
    - dmenv run -- python run-ci.py deploy
        --env ${CI_ENVIRONMENT_NAME} --git-tag ${CI_COMMIT_TAG}


mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
