stages:
  - check
  - deploy

before_script:
  - dmenv install

check/linux:
  stage: check
  except:
    - schedules
  script:
    - xvfb-run dmenv run -- python run-ci.py check --runner linux
    - mv coverage/lcov-report lcov-report
  artifacts:
    paths:
      - lcov-report/
    expire_in: 7 days
  tags:
    - linux

check/macos:
  stage: check
  except:
    - schedules
  script:
    - dmenv run -- python run-ci.py check --runner macos
  tags:
    - macos

.check/windows:
  stage: check
  tags:
    - windows
  allow_failure: true

check/windows/edge:
  extends: .check/windows
  script:
    - dmenv run -- python run-ci.py check --runner windows-edge

check/windows/ie:
  extends: .check/windows
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py check --runner windows-ie

check/windows/ie/manual:
  extends: .check/windows
  when: manual
  script:
    - dmenv run -- python run-ci.py check --runner windows-ie

check/linux/nightly:
  stage: check
  only:
    - schedules
  script:
    - xvfb-run dmenv run -- python run-ci.py check --runner linux --nightly
    - xvfb-run dmenv run -- python run-ci.py upgrade
  tags:
    - linux

check/macos/nightly:
  stage: check
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py check --runner macos --nightly
  tags:
    - macos

.deploy:
  stage: deploy
  except:
    - schedules
  tags:
    - linux

deploy/sdk:
  extends: .deploy
  environment:
    name: prod
  only:
    - /\Av[0-9.]+(-(alpha|beta)[0-9]+)?\z/
  script:
    - dmenv run -- python run-ci.py deploy
        --env ${CI_ENVIRONMENT_NAME} --git-tag ${CI_COMMIT_TAG}

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror

pages:
  stage: deploy
  only:
    - master
  except:
    - schedules
  dependencies:
    - check/linux
  script:
    - mv lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

check/upgrade:
  stage: check
  when: manual
  except:
    - master
  script:
    - xvfb-run dmenv run -- python run-ci.py upgrade
  tags:
    - linux

check/upgrade/master:
  stage: check
  only:
    - master
  script:
    - xvfb-run dmenv run -- python run-ci.py upgrade
  tags:
    - linux
