stages:
  - check
  - deploy

before_script:
  - python3 -m pipenv install --deploy

check/linux:
  stage: check
  except:
    - schedules
  script:
    - xvfb-run python3 -m pipenv run python ci/check.py --runner linux
  tags:
    - linux

check/macos:
  stage: check
  except:
    - schedules
  script:
    - python3 -m pipenv run python ci/check.py --runner macos
  tags:
    - macos

.check/windows:
  stage: check
  tags:
    - windows
  allow_failure: true

check/windows/edge:
  extends: .check/windows
  script:
    - python3 -m pipenv run python ci/check.py --runner windows-edge

check/windows/ie:
  extends: .check/windows
  only:
    - schedules
  script:
    - python3 -m pipenv run python ci/check.py --runner windows-ie

check/windows/ie/manual:
  extends: .check/windows
  when: manual
  script:
    - python3 -m pipenv run python ci/check.py --runner windows-ie

check/linux/nightly:
  stage: check
  only:
    - schedules
  script:
    - xvfb-run python3 -m pipenv run python ci/check.py --runner linux --nightly
  tags:
    - linux

check/macos/nightly:
  stage: check
  only:
    - schedules
  script:
    - python3 -m pipenv run python ci/check.py --runner macos --nightly
  tags:
    - macos

.deploy:
  stage: deploy
  except:
    - schedules
  tags:
    - linux

deploy/sdk:
  extends: .deploy
  environment:
    name: prod
  only:
    - /\Av[0-9.]+(-(alpha|beta)[0-9]+)?\z/
  script:
    - python3 -m pipenv run python ci/deploy.py
        --env ${CI_ENVIRONMENT_NAME} --git-tag ${CI_COMMIT_TAG}


mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  script:
    - python3 -m pipenv run python ci/mirror.py --ref ${CI_COMMIT_REF_NAME}
