language: node_js
node_js:
  - "node"  # latest stable

install:
  - yarn

matrix:
  include:
    - script:
        - yarn build:all
        - yarn coverage
        - yarn run codecov
      name: "Coverage"
    - script: yarn karma --browsers ChromeWindows
      name: "Latest Chrome on Windows"
    - script: yarn karma --browsers Chrome70Windows
      name: "Chrome 70 on Windows"
    - script: yarn karma --browsers EdgeWindows
      name: "Latest Edge"
    - script: yarn karma --browsers FirefoxWindows
      name: "Latest Firefox on Windows"
    - script: yarn karma --browsers Firefox64Windows
      name: "Firefox 64 on Windows"
    - script: yarn karma --browsers SafariMojave
      name: "Safari on Mojave"
    - script: yarn karma --browsers Android7
      name: "Chorme on android 7"
    - script: yarn karma --browsers Android5
      name: "Chorme on android 5"
